### ISSUE TITLE
Migrate to MUI v5

### ISSUE THREAD

**Issue by netzwerg** [netzwerg/react-you-do-you#34]

**Comment by protyze** [comment]
Shall we migrate to `tss-react` or start adopting `@emotion / styled` with MUI5? I think for us, it doesn't really make a difference regarding features (SSR-Support, Concurrent-Mode, etc…) and tss-react uses emotion under the hood (so performance and bundle size should be similar)? Thoughts? @netzwerg @denacem

**Comment by netzwerg** [comment]
@protyze I would migrate to `tss-react`. I didn't have any issues with v4's `makeStyles`, but `tss-react` is supposed to have better TypeScript support.

**Comment by netzwerg** [comment]
For the record:

`tss-react` was causing injection-order/caching issues, so I ended up using [MUI System](https://mui.com/system/basics/), the built-in CSS utilities.

Moreover, I couldn't get our old strategy of creating two `const` themes – light and dark – and toggling between them to work. Instead, `createTheme` has to be called anew whenever we pass it to the provider.
