### ISSUE TITLE
TSLint not hooked into build?

### ISSUE THREAD

**Issue by dmoles** [netzwerg/react-you-do-you#6]
The build is passing, but when I run `npx tslint --project .`, I get:

```
ERROR: /Users/la-dmoles/Scratch/react-you-do-you/src/__tests__/store/reducer.test.ts:38:13 - Identifier 'state' is never reassigned; use 'const' instead of 'let'.
ERROR: /Users/la-dmoles/Scratch/react-you-do-you/src/__tests__/theme/components/ThemeSwitch.test.tsx:8:68 - Lambdas are forbidden in JSX attributes due to their rendering performance impact
ERROR: /Users/la-dmoles/Scratch/react-you-do-you/src/__tests__/theme/components/ThemeSwitch.test.tsx:8:79 - unused expression, expected an assignment or function call
ERROR: /Users/la-dmoles/Scratch/react-you-do-you/src/__tests__/utils.ts:1:27 - block is empty
ERROR: /Users/la-dmoles/Scratch/react-you-do-you/src/__tests__/utils.ts:4:25 - block is empty
ERROR: /Users/la-dmoles/Scratch/react-you-do-you/src/chat/components/ChatErrors.tsx:36:13 - JSX elements with no children must be self-closing
```

Is there a way to hook TSLint into the build?

**Comment by dmoles** [comment]
(I'm finding examples that use gulp, but that feels like it might be overkill.)

**Comment by dmoles** [comment]
Here's what I've come up with so far for my own project, based on some other examples I've seen out in the wild (e.g. [TSLint itself](https://github.com/palantir/tslint/blob/master/package.json):

```json
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "tslint --project .",
    "prettify": "prettier --write 'src/**/*.{js,jsx,ts,tsx,json,css,scss,md}'",
    "lint-fix": "tslint --project . --fix",
    "coverage": "CI=true react-scripts test --coverage",
    "verify": "npm-run-all lint build coverage"
  },
```

Then customize the CI config to run the `verify` script instead of (the default) `test`, something like:

```yml
language: node_js

env:
  # without this, Jest seems to want to go into interactive watch mode
  CI=true

script:
  - npm run verify
```

**Comment by netzwerg** [comment]
Ouch, good catch, thank you! 😬

I integrated `tslint` into the husky pre-commit hook. While I was at it, I also added type checks of the test files, which always bothered me (https://github.com/facebook/create-react-app/issues/5626).

I did not integrate your `verify` command because I would like the scripts to work with either npm or yarn, but since everything is documented here now, people can copy/paste as they like and configure their CI accordingly.

**Comment by netzwerg** [comment]
I noticed that a fresh project created through `npx create-react-app --typescript` has perfect linting support hooked in. Reading [this blog post](https://dev.to/robertcoopercode/using-eslint-and-prettier-in-a-typescript-project-53jb) made me aware that we should get rid of TSLint all together and integrate the rules into ESLint (which supports TS).
